# Base configs
baseurl: "http://athuljayaraj.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-120452295-1"

# UI configs
title: "Photography by Athul"
subtitle: "See the world through my eyes!"
author: "Athul Raj"
header:
  title: "Photography"
  subtitle: "by Athul"
footer:
  name: "Hey there, my name is Athul"
  bio: "I am a photography enthusiast from Kerala, India."
  github: "Thanks to Ram Patra for the template. \n <a href=\"https://github.com/rampatra/photography\">Forked from here</a> ;)"
web_design: "AR"
social_urls:
  facebook: "https://www.facebook.com/athul.photography"
  instagram: "https://www.instagram.com/raj.athul"
  whatsapp: "https://api.whatsapp.com/send?phone=919947846480&text=Hi+Athul%2C+I+wanted+to+know+more+about+your+interest+in+photography"
