# Base configs
baseurl: "http://athuljayaraj.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Athul"
subtitle: "See the world through my eyes!"
author: "Athul Raj"
header:
 title: "Photography"
 subtitle: "by Ram Patra"
footer:
 name: "Hey there, my name is Athul"
 bio: "I am a developer from India."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AR"
social_urls:
  facebook: "https://www.facebook.com/athul.photography"
  twitter: "https://www.twitter.com/athulraj90"
  instagram: "https://www.instagram.com/raj.athul"
  dribbble: "https://dribbble.com/ramswaroop"
  linkedin: "https://in.linkedin.com/in/athulraj"
  github: "https://www.github.com/athuljayaraj"
